name:               calamity
version:            0.1.0.0
github:             "nitros12/calamity"
synopsis:           "A library for writing discord bots"
homepage:           "https://github.com/nitros12/calamity"
bug-reports:        "https://github.com/nitros12/calamity/issues"
license:            MIT
license-file:       LICENSE
author:             "Ben Simms"
maintainer:         "ben@bensimms.moe"
copyright:          "2020 Ben Simms"
category:           Network, Web

extra-source-files:
  - README.md
  - ChangeLog.md
  - cabal.project
  - cabal.project.freeze

extra-doc-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:        Please see the README on GitHub at <https://github.com/nitros12/calamity#readme>

dependencies:
- base-noprelude >= 4.12 && < 5
- websockets >= 0.12
- wuss >= 1.1
- wreq-patchable >= 0.5
- lens >= 4.18
- stm >= 2.5
- http-types >= 0.12
- aeson >= 1.4
- lens-aeson >= 1.1
- typerep-map >= 0.3
- protolude >= 0.2
- generic-lens >= 2.0
- text >= 1.2
- exceptions >= 0.10
- fmt >= 0.6
- stm-containers >= 1.1
- stm-chans >= 3.0
- concurrent-extra >= 0.7
- focus >= 1.0
- data-default-class >= 0.1
- hashable >= 1.2
- time >= 1.8  # aeson dep
- unordered-containers >= 0.2
- http-date >= 0.0.8
- bytestring >= 0.10
- async >= 2.2
- scientific >= 0.3
- deque >= 0.1
- text-short >= 0.1
- vector >= 0.12
- reflection >= 2.1
- polysemy >= 1.3
- polysemy-plugin >= 0.2
- di-polysemy >= 0.0.2
- df1 >= 0.3
- generic-override >= 0.0.0.1
- generic-override-aeson >= 0.0.0.1

# executables:
#   test-calamity-exe:
#     main: Main.hs
#     source-dirs: app
#     ghc-options:
#       - -fplugin=Polysemy.Plugin
#       - -funbox-strict-fields
#       - -flate-specialise
#       - -threaded
#       - -rtsopts
#       - -with-rtsopts=-T
#       - -O2
#     dependencies:
#       - calamity

library:
  ghc-options:
    - -fplugin=Polysemy.Plugin
    - -funbox-strict-fields
    - -Wall
  source-dirs: src

default-extensions:
  - CPP
  - AllowAmbiguousTypes
  - BlockArguments
  - NoMonomorphismRestriction
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - UndecidableInstances
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - DerivingVia
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  - DeriveAnyClass
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - OverloadedLabels
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns
  - DuplicateRecordFields
  - TypeOperators
  - TypeApplications
  - RoleAnnotations
