name:               calamity
version:            0.1.0.0
github:             "nitros12/calamity"
license:            MIT
author:             "Ben Simms"
maintainer:         "ben@bensimms.moe"
copyright:          "2018 Ben Simms"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:        Please see the README on GitHub at <https://github.com/nitros12/calamity#readme>

dependencies:
- base-noprelude >= 4.12 && < 5
- websockets >= 0.12
- wuss >= 1.1
- wreq >= 0.5
- lens >= 4.17
- stm >= 2.5
- http-types >= 0.12
- aeson >= 1.4
- lens-aeson >= 1.1
- typerep-map >= 0.3
- protolude >= 0.2
- streamly >= 0.7
- generic-lens >= 1.2
- transformers >= 0.5
- mtl >= 2.2
- text >= 1.2
- concurrent-state >= 0.6
- exceptions >= 0.10
- fmt >= 0.6
- stm-containers >= 1.1
- stm-chans >= 3.0
- concurrent-extra >= 0.7
- focus >= 1.0
- data-default-extra >= 0.1.0
- hashable >= 1.2
- time >= 1.8  # aeson dep
- unordered-containers >= 0.2
- http-date >= 0.0.8
- bytestring >= 0.10
- monad-control >= 1.0
- transformers-base >= 0.4
- async >= 2.2
- simple-log >= 0.9
- scientific >= 0.3
- pqueue >= 1.4
- text-short >= 0.1
- vector >= 0.12
- reflection >= 2.1
- polysemy >= 0.3
- polysemy-plugin >= 0.2
- di-polysemy
- df1

executables:
  test-calamity-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -fplugin=Polysemy.Plugin
      - -funbox-strict-fields
      - -threaded
      - -rtsopts
      - -with-rtsopts=-T
      - -O3
    dependencies:
      - calamity

flags:
  parse-presences:
    description: If the library should parse presences or not
    manual: false
    default: true

library:
  ghc-options:
    - -fplugin=Polysemy.Plugin
    - -funbox-strict-fields
    - -Wall
  when:
    - condition: flag(parse-presences)
      then:
        cpp-options:
          - -DPARSE_PRESENCES
      else:
        cpp-options: []

  source-dirs: src

default-extensions:
  - CPP
  - AllowAmbiguousTypes
  - BlockArguments
  - NoMonomorphismRestriction
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - UndecidableInstances
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - DerivingVia
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  - DeriveAnyClass
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - OverloadedLabels
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns
  - DuplicateRecordFields
  - TypeOperators
  - TypeApplications
  - RoleAnnotations

tests:
  calamity-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calamity
